from collections import OrderedDict
import sys

idir = sys.argv[1]

# FLEURS (https://huggingface.co/datasets/google/xtreme_s/blob/main/xtreme_s.py)

_FLEURS_LANG_TO_ID = OrderedDict(
    [
        ("Afrikaans", "af"),
        ("Amharic", "am"),
        ("Arabic", "ar"),
        ("Armenian", "hy"),
        ("Assamese", "as"),
        ("Asturian", "ast"),
        ("Azerbaijani", "az"),
        ("Belarusian", "be"),
        ("Bengali", "bn"),
        ("Bosnian", "bs"),
        ("Bulgarian", "bg"),
        ("Burmese", "my"),
        ("Catalan", "ca"),
        ("Cebuano", "ceb"),
        ("Mandarin Chinese", "cmn_hans"),
        ("Cantonese Chinese", "yue_hant"),
        ("Croatian", "hr"),
        ("Czech", "cs"),
        ("Danish", "da"),
        ("Dutch", "nl"),
        ("English", "en"),
        ("Estonian", "et"),
        ("Filipino", "fil"),
        ("Finnish", "fi"),
        ("French", "fr"),
        ("Fula", "ff"),
        ("Galician", "gl"),
        ("Ganda", "lg"),
        ("Georgian", "ka"),
        ("German", "de"),
        ("Greek", "el"),
        ("Gujarati", "gu"),
        ("Hausa", "ha"),
        ("Hebrew", "he"),
        ("Hindi", "hi"),
        ("Hungarian", "hu"),
        ("Icelandic", "is"),
        ("Igbo", "ig"),
        ("Indonesian", "id"),
        ("Irish", "ga"),
        ("Italian", "it"),
        ("Japanese", "ja"),
        ("Javanese", "jv"),
        ("Kabuverdianu", "kea"),
        ("Kamba", "kam"),
        ("Kannada", "kn"),
        ("Kazakh", "kk"),
        ("Khmer", "km"),
        ("Korean", "ko"),
        ("Kyrgyz", "ky"),
        ("Lao", "lo"),
        ("Latvian", "lv"),
        ("Lingala", "ln"),
        ("Lithuanian", "lt"),
        ("Luo", "luo"),
        ("Luxembourgish", "lb"),
        ("Macedonian", "mk"),
        ("Malay", "ms"),
        ("Malayalam", "ml"),
        ("Maltese", "mt"),
        ("Maori", "mi"),
        ("Marathi", "mr"),
        ("Mongolian", "mn"),
        ("Nepali", "ne"),
        ("Northern-Sotho", "nso"),
        ("Norwegian", "nb"),
        ("Nyanja", "ny"),
        ("Occitan", "oc"),
        ("Oriya", "or"),
        ("Oromo", "om"),
        ("Pashto", "ps"),
        ("Persian", "fa"),
        ("Polish", "pl"),
        ("Portuguese", "pt"),
        ("Punjabi", "pa"),
        ("Romanian", "ro"),
        ("Russian", "ru"),
        ("Serbian", "sr"),
        ("Shona", "sn"),
        ("Sindhi", "sd"),
        ("Slovak", "sk"),
        ("Slovenian", "sl"),
        ("Somali", "so"),
        ("Sorani-Kurdish", "ckb"),
        ("Spanish", "es"),
        ("Swahili", "sw"),
        ("Swedish", "sv"),
        ("Tajik", "tg"),
        ("Tamil", "ta"),
        ("Telugu", "te"),
        ("Thai", "th"),
        ("Turkish", "tr"),
        ("Ukrainian", "uk"),
        ("Umbundu", "umb"),
        ("Urdu", "ur"),
        ("Uzbek", "uz"),
        ("Vietnamese", "vi"),
        ("Welsh", "cy"),
        ("Wolof", "wo"),
        ("Xhosa", "xh"),
        ("Yoruba", "yo"),
        ("Zulu", "zu"),
    ]
)
_FLEURS_LANG_SHORT_TO_LONG = {v: k for k, v in _FLEURS_LANG_TO_ID.items()}


_FLEURS_LANG = sorted(
    [
        "af_za",
        "am_et",
        "ar_eg",
        "as_in",
        "ast_es",
        "az_az",
        "be_by",
        "bn_in",
        "bs_ba",
        "ca_es",
        "ceb_ph",
        "cmn_hans_cn",
        "yue_hant_hk",
        "cs_cz",
        "cy_gb",
        "da_dk",
        "de_de",
        "el_gr",
        "en_us",
        "es_419",
        "et_ee",
        "fa_ir",
        "ff_sn",
        "fi_fi",
        "fil_ph",
        "fr_fr",
        "ga_ie",
        "gl_es",
        "gu_in",
        "ha_ng",
        "he_il",
        "hi_in",
        "hr_hr",
        "hu_hu",
        "hy_am",
        "id_id",
        "ig_ng",
        "is_is",
        "it_it",
        "ja_jp",
        "jv_id",
        "ka_ge",
        "kam_ke",
        "kea_cv",
        "kk_kz",
        "km_kh",
        "kn_in",
        "ko_kr",
        "ckb_iq",
        "ky_kg",
        "lb_lu",
        "lg_ug",
        "ln_cd",
        "lo_la",
        "lt_lt",
        "luo_ke",
        "lv_lv",
        "mi_nz",
        "mk_mk",
        "ml_in",
        "mn_mn",
        "mr_in",
        "ms_my",
        "mt_mt",
        "my_mm",
        "nb_no",
        "ne_np",
        "nl_nl",
        "nso_za",
        "ny_mw",
        "oc_fr",
        "om_et",
        "or_in",
        "pa_in",
        "pl_pl",
        "ps_af",
        "pt_br",
        "ro_ro",
        "ru_ru",
        "bg_bg",
        "sd_in",
        "sk_sk",
        "sl_si",
        "sn_zw",
        "so_so",
        "sr_rs",
        "sv_se",
        "sw_ke",
        "ta_in",
        "te_in",
        "tg_tj",
        "th_th",
        "tr_tr",
        "uk_ua",
        "umb_ao",
        "ur_pk",
        "uz_uz",
        "vi_vn",
        "wo_sn",
        "xh_za",
        "yo_ng",
        "zu_za",
    ]
)
_FLEURS_LONG_TO_LANG = {
    _FLEURS_LANG_SHORT_TO_LONG["_".join(k.split("_")[:-1]) or k]: k
    for k in _FLEURS_LANG
}
_FLEURS_LANG_TO_LONG = {v: k for k, v in _FLEURS_LONG_TO_LANG.items()}

# Common Voice (https://github.com/common-voice/common-voice/blob/main/web/locales/en/messages.ftl)

_CV_LANG_TO_LONG = OrderedDict(
    [
        ("ab", "Abkhaz"),
        ("ace", "Acehnese"),
        ("ady", "Adyghe"),
        ("af", "Afrikaans"),
        ("am", "Amharic"),
        ("an", "Aragonese"),
        ("ar", "Arabic"),
        ("arn", "Mapudungun"),
        ("as", "Assamese"),
        ("ast", "Asturian"),
        ("az", "Azerbaijani"),
        ("ba", "Bashkir"),
        ("bas", "Basaa"),
        ("be", "Belarusian"),
        ("bg", "Bulgarian"),
        ("bm", "Bambara"),
        ("bn", "Bengali"),
        ("bo", "Tibetan"),
        ("br", "Breton"),
        ("bs", "Bosnian"),
        ("bxr", "Buryat"),
        ("byv", "Medumba"),
        ("ca", "Catalan"),
        ("cak", "Kaqchikel"),
        ("ckb", "Central Kurdish"),
        ("cnh", "Hakha Chin"),
        ("co", "Corsican"),
        ("cs", "Czech"),
        ("cv", "Chuvash"),
        ("cy", "Welsh"),
        ("da", "Danish"),
        ("dag", "Dagbani"),
        ("de", "German"),
        ("dsb", "Sorbian, Lower"),
        ("dv", "Dhivehi"),
        ("dyu", "Dioula"),
        ("el", "Greek"),
        ("en", "English"),
        ("eo", "Esperanto"),
        ("es", "Spanish"),
        ("et", "Estonian"),
        ("eu", "Basque"),
        ("fa", "Persian"),
        ("ff", "Fulah"),
        ("fi", "Finnish"),
        ("fo", "Faroese"),
        ("fr", "French"),
        ("fy-NL", "Frisian"),
        ("ga-IE", "Irish"),
        ("gl", "Galician"),
        ("gn", "Guarani"),
        ("gom", "Goan Konkani"),
        ("ha", "Hausa"),
        ("he", "Hebrew"),
        ("hi", "Hindi"),
        ("hil", "Hiligaynon"),
        ("hr", "Croatian"),
        ("hsb", "Sorbian, Upper"),
        ("ht", "Haitian"),
        ("hu", "Hungarian"),
        ("hy-AM", "Armenian"),
        ("hyw", "Armenian Western"),
        ("ia", "Interlingua"),
        ("id", "Indonesian"),
        ("ie", "Interlingue"),
        ("ig", "Igbo"),
        ("is", "Icelandic"),
        ("it", "Italian"),
        ("izh", "Izhorian"),
        ("ja", "Japanese"),
        ("jbo", "Lojban"),
        ("ka", "Georgian"),
        ("kaa", "Karakalpak"),
        ("kab", "Kabyle"),
        ("kbd", "Kabardian"),
        ("ki", "Kikuyu"),
        ("kk", "Kazakh"),
        ("km", "Khmer"),
        ("kmr", "Kurmanji Kurdish"),
        ("kn", "Kannada"),
        ("knn", "Konkani (Devanagari)"),
        ("ko", "Korean"),
        ("kpv", "Komi-Zyrian"),
        ("kw", "Cornish"),
        ("ky", "Kyrgyz"),
        ("lb", "Luxembourgish"),
        ("lg", "Luganda"),
        ("lij", "Ligurian"),
        ("ln", "Lingala"),
        ("lo", "Lao"),
        ("lt", "Lithuanian"),
        ("lv", "Latvian"),
        ("mai", "Maithili"),
        ("mdf", "Moksha"),
        ("mg", "Malagasy"),
        ("mhr", "Meadow Mari"),
        ("mk", "Macedonian"),
        ("ml", "Malayalam"),
        ("mn", "Mongolian"),
        ("mni", "Meetei Lon"),
        ("mos", "Mossi"),
        ("mr", "Marathi"),
        ("mrj", "Hill Mari"),
        ("ms", "Malay"),
        ("mt", "Maltese"),
        ("my", "Burmese"),
        ("myv", "Erzya"),
        ("nan-tw", "Taiwanese (Minnan)"),
        ("nb-NO", "Norwegian Bokmål"),
        ("nd", "IsiNdebele (North)"),
        ("ne-NP", "Nepali"),
        ("nhe", "Eastern Huasteca Nahuatl"),
        ("nhi", "Western Sierra Puebla Nahuatl"),
        ("nia", "Nias"),
        ("nl", "Dutch"),
        ("nn-NO", "Norwegian Nynorsk"),
        ("nr", "IsiNdebele (South)"),
        ("nso", "Northern Sotho"),
        ("ny", "Chinyanja"),
        ("nyn", "Runyankole"),
        ("oc", "Occitan"),
        ("om", "Afaan Oromo"),
        ("or", "Odia"),
        ("pa-IN", "Punjabi"),
        ("pap-AW", "Papiamento (Aruba)"),
        ("pl", "Polish"),
        ("ps", "Pashto"),
        ("pt", "Portuguese"),
        ("quc", "K'iche'"),
        ("quy", "Quechua Chanka"),
        ("rm-sursilv", "Romansh Sursilvan"),
        ("rm-vallader", "Romansh Vallader"),
        ("ro", "Romanian"),
        ("ru", "Russian"),
        ("rw", "Kinyarwanda"),
        ("sah", "Sakha"),
        ("sat", "Santali (Ol Chiki)"),
        ("sc", "Sardinian"),
        ("scn", "Sicilian"),
        ("sdh", "Southern Kurdish"),
        ("shi", "Shilha"),
        ("si", "Sinhala"),
        ("sk", "Slovak"),
        ("skr", "Saraiki"),
        ("sl", "Slovenian"),
        ("snk", "Soninke"),
        ("so", "Somali"),
        ("sq", "Albanian"),
        ("sr", "Serbian"),
        ("ss", "Siswati"),
        ("st", "Southern Sotho"),
        ("sv-SE", "Swedish"),
        ("sw", "Swahili"),
        ("syr", "Syriac"),
        ("ta", "Tamil"),
        ("te", "Telugu"),
        ("tg", "Tajik"),
        ("th", "Thai"),
        ("ti", "Tigrinya"),
        ("tig", "Tigre"),
        ("tk", "Turkmen"),
        ("tl", "Tagalog"),
        ("tn", "Setswana"),
        ("tok", "Toki Pona"),
        ("tr", "Turkish"),
        ("ts", "Xitsonga"),
        ("tt", "Tatar"),
        ("tw", "Twi"),
        ("ty", "Tahitian"),
        ("tyv", "Tuvan"),
        ("uby", "Ubykh"),
        ("udm", "Udmurt"),
        ("ug", "Uyghur"),
        ("uk", "Ukrainian"),
        ("ur", "Urdu"),
        ("uz", "Uzbek"),
        ("ve", "Tshivenda"),
        ("vec", "Venetian"),
        ("vi", "Vietnamese"),
        ("vot", "Votic"),
        ("wo", "Wolof"),
        ("xh", "Xhosa"),
        ("yi", "Yiddish"),
        ("yo", "Yoruba"),
        ("yue", "Cantonese"),
        ("zgh", "Tamazight"),
        ("zh-CN", "Chinese (China)"),
        ("zh-HK", "Chinese (Hong Kong)"),
        ("zh-TW", "Chinese (Taiwan)"),
        ("zu", "Zulu"),
        ("zza", "Zaza"),
    ]
)

# patch CV names to match FLEURS names
_CV_LANG_TO_LONG["nb-NO"] = "Norwegian"
_CV_LANG_TO_LONG["nn-NO"] = "Norwegian"
_CV_LANG_TO_LONG["ckb"] = "Sorani-Kurdish"
_CV_LANG_TO_LONG["zh-CN"] = "Mandarin Chinese"
_CV_LANG_TO_LONG["zh-HK"] = "Mandarin Chinese"
_CV_LANG_TO_LONG["zh-TW"] = "Mandarin Chinese"
_CV_LANG_TO_LONG["ff"] = "Fula"
_CV_LANG_TO_LONG["om"] = "Oromo"
_CV_LANG_TO_LONG["nso"] = "Northern-Sotho"
_CV_LANG_TO_LONG["yue"] = "Cantonese Chinese"


_FLEURS_LONG = set([v for v in _FLEURS_LANG_TO_LONG.values()])
_CV_LONG = set([v for v in _CV_LANG_TO_LONG.values()])


utt2lang = {"train_t_sp": {}, "dev_fleurs": {}}

for dset in utt2lang:
    with open(f"{idir}/{dset}/wav.scp") as wavscp:
        for l in wavscp:
            utt = l[: l.index(" ")]
            if "common_voice" in utt:
                lang_code = utt.split("_")[-2]
                lang = _CV_LANG_TO_LONG[lang_code]
            else:
                lang_code = utt.split("-")[-4]
                lang = _FLEURS_LANG_TO_LONG[lang_code]

            utt2lang[dset][utt] = lang

_ALL_LANG = sorted(
    [
        x
        for x in (_FLEURS_LONG | _CV_LONG)
        & set(utt2lang[d][l] for d in utt2lang for l in utt2lang[d])
    ]
)

for dset in utt2lang:
    with open(f"{idir}/{dset}/utt2lid_token", "w") as f:
        for utt in sorted(utt2lang[dset].keys()):
            f.write(f"{utt} {_ALL_LANG.index(utt2lang[dset][utt])+1}\n")
